all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
prod:
  hosts:
    client1:
      ansible_host: 192.168.99.11
    client2:
      ansible_host: 192.168.99.12
  vars:
    env: production

